version: 0.2

phases:
  install:
    # Definir el runtime adecuado
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo Ejecutar comando de pruebas pytest
      - pytest
